server:
  port: 8082

spring:
  main:
    banner-mode: "off"
  application:
    name: dos-registry-service

logging:
  level:
    org.keycloak: trace
    org.springframework.security: trace

keycloak:
  enable-basic-auth: false  # basic auth is default true, we dont want that
  realm: SpringBootKeycloak   # our keycloak realm this ressource service should be based in
  auth-server-url: http://localhost:8180/auth  # the url to our sso server (keycloak)
  ssl-required: external  # no ssl is ok for demo  - do not use this in production
  resource: demo-client  # the realm-client which accessing clients should be authenticate with
  use-resource-role-mappings: true # use this if you manage your roles in client scope not in realm scope
  public-client: false # we do not write a web-app - so no login page and redirects are necessary
  bearer-only: true  # authentification via accesstoken is fine
  #principal-attribute: preferred_username #This enables application to use @EnableWebSecurity annotation
  securityConstraints:
  -   authRoles:
      - demo-user-role   # the authenticated user needs this role to be authorized to access this ressource
      securityCollections:
      -   name: acces only with auth # just a comment
          patterns:
          - /message  # the actual rest endpoint which shoulb be protected
