server:
  port: 8083

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: DNAstack
  resource: dos-registry
  public-client: false
  principal-attribute: preferred_username
  bearer-only: true
  enable-basic-auth: false # basic auth is default true, we dont want that
  cors: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    # Use Jadira Usertype for mapping Joda Time types
    # For Hibernate native properties must be used spring.jpa.properties.* (the
    # prefix is stripped before adding them to the entity manager).
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true

logging:
    level:
        org.springframework.ws.client.MessageTracing.sent: TRACE
        org.springframework.ws.client.MessageTracing.received: TRACE
        org.apache.http.wire: DEBUG
        org.springframework: DEBUG
        org.springframework.web.client.RestTemplate: DEBUG
        org.keycloak.adapters.springsecurity: TRACE